// Strategy tips shown on the player's role card (one per peek, cycling). Keyed by the role's name in
// ./roleLibrary.ts; built-in roles use their library name (e.g. the built-in Sorceress is 'Sorcerer').
// Translations: ./i18n/tips.<lang>.ts (same keys). Roles without tips fall back to their team's tips.

export const TEAM_TIPS: Record<'Village' | 'Werewolves' | 'Loner', string[]> = {
  Village: [
    'Watch who changes their story — liars have to remember what they said.',
    'Ask quiet players what they think. Wolves love to hide in silence.',
    'Don’t vote just because everyone else does. Ask why first.',
  ],
  Werewolves: [
    'Act exactly like a villager: suspect, accuse, and vote with the crowd.',
    'Don’t defend your packmates too hard — it links you together.',
    'Pick night victims who are trusted or sharp, not the loudest player.',
  ],
  Loner: [
    'Nobody is on your side — let the village and the wolves wear each other down.',
    'Stay forgettable early. Make your move when the table is small.',
    'Lean whichever way keeps you alive today; switch tomorrow if you must.',
  ],
};

export const ROLE_TIPS: Record<string, string[]> = {
  // ---------- Village ----------
  'Villager': ['You have no power — your vote and your voice are your weapons.', 'Keep notes in your head: who accused whom, and who changed their vote.', 'Claiming a power role can protect the real one — but only if you’re sure.'],
  'Seer': ['Don’t reveal yourself too early — you become the wolves’ first target.', 'Check loud accusers and quiet players; they’re the most telling.', 'When you find a wolf, steer the vote without saying how you know.'],
  'Apprentice Seer': ['Stay quiet: the wolves don’t know you exist yet.', 'Remember what the Seer hinted — you may need to finish their work.', 'Once you take over, act like nothing has changed.'],
  'Aura Seer': ['A nod means a special role — not necessarily a villager.', 'A plain Villager and a plain Werewolf both get a shake.', 'Combine your nods with the Seer’s checks to narrow down the wolves.'],
  'Medium': ['The dead’s roles tell you which powers are still in play.', 'If a dead player was a wolf, look at who defended them.', 'Hint at what you learned instead of announcing it.'],
  'Witch': ['Don’t waste the healing potion on night one unless the victim is key.', 'Save the poison for a wolf you’re almost sure about.', 'Once a potion is used, play as if you still have it — make the wolves nervous.'],
  'Healer': ['Protecting yourself early can keep a power role alive longer.', 'Guess who the wolves fear most — that’s who to protect.', 'Never say whom you protected; it tells the wolves where not to strike.'],
  'Bodyguard': ['You die in place of the player you guard — choose someone worth it.', 'Guard the player who’s shown the most insight; they’re the wolves’ target.', 'Your sacrifice proves your role — the village will trust your last guard.'],
  'Hunter': ['Act a little suspicious; wolves won’t want to kill you at night.', 'Pick your shot early in your head — you may not get time to think.', 'If you’re voted out, aim at the player who pushed hardest for it.'],
  'Investigator': ['One of the three roles is real — compare with what they’ve claimed.', 'Investigate players who claim power roles to test their story.', 'Keep your list private until it can swing a vote.'],
  'Tracker': ['A player who “visited” someone at night has a night power — or is a wolf.', 'Track the players the village trusts least first.', 'Two players visiting the same victim is a huge clue.'],
  'Watcher': ['Watch the player you think the wolves will attack next.', 'Whoever visits the victim is probably a wolf — or a protector.', 'Your results are strongest when matched with the Tracker’s.'],
  'Priest': ['Your blessing works once — save it for a player you’re sure is good.', 'Blessing a confirmed power role can win the game.', 'Keep the blessing secret so the wolves waste a kill.'],
  'Mason': ['You know your fellow Mason is good — use each other as anchors.', 'Don’t both reveal at once; one hidden Mason is safer.', 'Vouch for each other only when it really matters.'],
  'Mayor': ['Reveal when your double vote can decide an important elimination.', 'Once revealed you’re a target — make that vote count.', 'Before revealing, quietly see who tries to sway you.'],
  'Judge': ['Call the second vote when the first one hits an obvious innocent.', 'Use it once — choose the moment the village is about to make a mistake.', 'Watch who is relieved after a vote; that player may be a wolf.'],
  'Prince': ['You survive your first vote — don’t be afraid to make bold accusations.', 'Being voted reveals you; afterwards your word carries weight.', 'Bait the wolves into pushing a vote on you.'],
  'Elder': ['You survive one wolf attack — the wolves may waste a night on you.', 'After surviving, the village knows you’re no wolf. Lead.', 'Act bold early; you can afford to.'],
  'Little Girl': ['Peek only a little — if the wolves see you, you’re next.', 'Don’t say you peeked; steer votes with “gut feelings”.', 'Even one wolf’s face is enough to win the day.'],
  'Hunter Apprentice': ['Stay low until the Hunter falls.', 'Once you inherit the bow, keep it secret until your last moment.', 'Note who the Hunter suspected — that’s your future target.'],
  'Pacifist': ['You can’t vote to eliminate — use your words to persuade instead.', 'Your refusal to vote can make wolves think you’re harmless.', 'Defend players you believe are innocent; that’s your power.'],
  'Fortune Teller': ['Your exact-role check works once — use it on a big claim.', 'Check the player most likely to be lying about a power.', 'Reveal the result only when it can decide a vote.'],
  'Baker': ['While you live, the village is fed — stay alive.', 'If you die, the village starts losing players — warn them early if wolves eye you.', 'Make friends with the protectors.'],
  'Revealer': ['Only use your power when you’re very sure — a miss kills you.', 'Target someone the Seer or Watcher has already hinted at.', 'Waiting a few nights for more clues is often smarter.'],
  'Spy': ['You’ll learn one wolf — don’t rush to name them.', 'Watch who that wolf protects in talks; they may be packmates.', 'Lead the vote with logic, not with “I saw it”.'],
  'Robber': ['Swap with a player whose role might be powerful.', 'Act as if you’re still your old role for a while.', 'Remember: the player you robbed now has your old card.'],
  'Troublemaker': ['Swap two players you suspect — confusion hurts the wolves most.', 'Don’t tell anyone whom you swapped.', 'Watch the swapped players’ reactions the next morning.'],
  'Drunk': ['Play as a Villager for now — your real role is coming.', 'Don’t make claims you can’t back up later.', 'When your role arrives, use it quietly.'],
  'Insomniac': ['A nod means one of your neighbours has a night power.', 'Two shakes in a row hint that both neighbours are plain Villagers.', 'Share it only if it helps the village.'],
  'Mimic': ['Copy someone whose power you think matters most.', 'Copying a good player helps — they could cover for each other.', 'Your team doesn’t change; only your power does.'],
  'Doppelgänger': ['Copy a player you think has a strong role — you’ll inherit it.', 'You win with the team of the role you copied — watch your target.', 'Stay neutral in talks until you know what you’ll become.'],
  'Cursed': ['If the wolves bite you, you join them — so maybe let them.', 'Until then, help the village honestly.', 'If you turn, keep acting exactly the same.'],
  'Diseased': ['If the wolves eat you, they skip a night — be a tempting target.', 'Make the wolves think you’re a power role.', 'Your death buys the village a free night.'],
  'Lycan': ['The Seer sees you as a wolf — be ready to defend yourself.', 'Stay calm and consistent; panic looks guilty.', 'Ask for a second check by another role if you can.'],
  'Tough Guy': ['If the wolves attack you, you won’t be told — you just die the next night.', 'Speak up every day as if it might be your last.', 'The wolves may waste a night on you.'],
  'Village Idiot': ['You must always vote to eliminate — make your votes look smart.', 'Play the fool; wolves rarely kill harmless-looking players.', 'Your forced votes can bait wolves into revealing themselves.'],
  'Old Hag': ['Banish a loud suspect so the village hears other voices.', 'Banishing a power role can protect them from a vote.', 'Vary whom you banish so nobody can tell it’s you.'],

  // ---------- Werewolf ----------
  'Werewolf': ['Vote with the majority — standing out gets wolves caught.', 'Kill the player who is getting closest to the truth.', 'Throw a little suspicion on a quiet villager.'],
  'Alpha Werewolf': ['Turning a villager can be stronger than killing one — pick a trusted player.', 'Save your conversion for when the pack is losing numbers.', 'Lead the pack quietly; don’t look like a leader by day.'],
  'Wolf Cub': ['If you die, the pack gets two victims — be a little bold.', 'Let suspicion fall on you if it protects an older wolf.', 'Your death is a weapon; time it well.'],
  'White Werewolf': ['You win alone — help the pack until the end is near.', 'Eliminate the wolf who could beat you in the final.', 'Never let the pack know you’re not one of them.'],
  'Wolf King': ['If you go down, take a strong villager with you.', 'Choose your final target before the day starts.', 'Act confident; the village fears killing a powerful player.'],
  'Nightmare Wolf': ['Block the Seer or protector on key nights.', 'Blocking at random keeps them guessing.', 'Use your power the night the pack plans its best kill.'],
  'Shadow Wolf': ['Checks show you as a villager — volunteer to be checked.', 'Use your “clean” result to lead the vote.', 'Don’t overplay it; too much confidence looks fake.'],
  'Omega Wolf': ['Stay quiet while the pack is big.', 'When you’re the last wolf, your double kill can turn the game.', 'Survive at all costs — you’re the pack’s last hope.'],
  'Big Bad Wolf': ['Your extra kill works only while no wolf has died — strike early.', 'Pick a victim sitting next to a power role.', 'Protect your packmates in talks; one loss ends your bonus.'],
  'Sorcerer': ['You’re hunting the Seer — find them for the pack.', 'Once found, hint it to the pack without exposing yourself.', 'Act like a confused villager by day.'],
  'Minion': ['You know the wolves, they don’t know you — protect them quietly.', 'Take suspicion yourself to save a wolf.', 'Fake-claiming a power role can confuse the village.'],
  'Traitor': ['You win with the wolves but don’t know them — read the table.', 'Push votes against confirmed villagers.', 'Every check shows you as good — use that trust.'],

  // ---------- Neutral / Loner ----------
  'Tanner': ['Act just suspicious enough — too obvious and they won’t vote you.', 'Argue weakly, contradict yourself a little.', 'Get voted out and you win — everyone else loses.'],
  'Serial Killer': ['The wolves can’t kill you — use that to stay calm.', 'Kill whoever threatens you most, villager or wolf.', 'Let the village and wolves fight; you just need to be last.'],
  'Arsonist': ['Douse quietly for a few nights before you light.', 'Douse the players most likely to survive long.', 'One big fire can win the game in a single night.'],
  'Vampire': ['Bite players who seem loyal and quiet.', 'Grow your coven before anyone notices.', 'Protect your vampires in the vote.'],
  'Vampire Hunter': ['Listen for players who suddenly change sides.', 'Your check kills a vampire — choose carefully.', 'You win with the village, so help them too.'],
  'Necromancer': ['Raise a dead player with a powerful role.', 'Wait until the right player has fallen.', 'Your raised ally can surprise everyone.'],
  'Executioner': ['Make your target look suspicious without looking obsessed.', 'Push the vote on your target on the right day.', 'Agree with others when they accuse your target.'],
  'Survivor': ['Avoid making enemies — be everyone’s second choice.', 'Never lead a vote; follow safely.', 'Stay alive until the end and you win.'],
  'Alien': ['You need to be one of the last three — stay neutral.', 'Help eliminate whoever would leave you out.', 'Don’t look like a threat to either side.'],
  'Devil': ['Make deals with players who look likely to survive.', 'Protect your dealers in the vote.', 'Keep your deals secret.'],
  'Death': ['Mark players who are likely to be voted for.', 'Spread your marks across both teams.', 'Patience — your marks pay off when votes fall.'],
  'Angel': ['You win if you go out early — act suspicious on day one.', 'After that, you’re a villager — help them.', 'Don’t overdo it; obvious bait gets ignored.'],
  'Fallen Angel': ['Curse players who are leading the village.', 'Silenced votes can tip the game toward chaos.', 'Stay hidden; you win when the village falls.'],
  'Cupid': ['Link two players from different teams for chaos.', 'Linking yourself can secure a strong ally.', 'Watch the lovers — one death takes both.'],

  // ---------- Special ----------
  'King': ['Cancel a vote that’s about to eliminate an innocent.', 'Use it once — make it count.', 'Your power reveals you; be ready to be targeted.'],
  'Lawyer': ['Keep your client alive — defend them in every vote.', 'Don’t make your loyalty obvious.', 'Your client’s death means your loss.'],
  'Blackmailer': ['Silence the player who’s closest to exposing a wolf.', 'Vary your targets so you don’t look obvious.', 'A silenced Seer can’t share what they know.'],
  'Hypnotist': ['Force a strong villager to vote against their own side.', 'Use it on decisive votes.', 'Keep your control subtle.'],
  'Illusionist': ['Disguise a wolf the night the Seer is likely to check.', 'Disguising a villager can frame them.', 'Your illusions work best when checks are trusted.'],
  'Spellcaster': ['Silence a player you suspect so they can’t lead the day.', 'Silencing a loud wolf weakens the pack.', 'Vary your targets to stay hidden.'],
  'Gambler': ['Bet on players the wolves are most likely to attack.', 'Watch who the wolves seem to fear.', 'Three right guesses win it — be patient.'],
  'Bartender': ['Block players you suspect of night powers.', 'Blocking a wolf can save a life.', 'Vary your targets.'],
  'Vengeful Spirit': ['If you die, remember who did it.', 'Your revenge strikes once — make it the right player.', 'Living or dead, keep watching.'],
  'Ghost': ['You give one letter a day — make it count.', 'Pick letters that point at a wolf’s name.', 'Never give a whole name; one letter is the rule.'],
  'Poltergeist': ['After death, cancel the vote that would hurt the village most.', 'Wait for the right moment to knock.', 'Your knock can save an innocent.'],
};
